// Regenerate utils/dara/legal-content.ts from the .docx files in public/legal/.
//
// The .docx files in public/legal/ are the source of truth (they are also what users
// download). This script extracts their text for in-app rendering and stamps the version
// + effective date parsed from the Terms of Service.
//
// USAGE — after replacing/adding a doc in public/legal/, bump LEGAL_VERSION in the doc's
// "Version x.y" line if applicable, then run:
//   node scripts/gen-legal.mjs
// and commit both the .docx and the regenerated utils/dara/legal-content.ts.

import mammoth from 'mammoth';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// id → { title, file }. Add entries here when new legal docs are introduced.
const DOCS = [
  {
    id: 'terms',
    title: 'Terms of Service & Legal Document Set',
    file: 'DARA_Legal_Document_Set_v1.0.docx'
  },
  {
    id: 'addendum',
    title: 'Supplemental Policy Addendum (Exhibits C–I)',
    file: 'DARA_Supplemental_Policy_Addendum_v1.0.docx'
  }
];

function clean(text) {
  return text
    .replace(/\r/g, '')
    .split('\n')
    .map((l) => l.replace(/\s+$/g, ''))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

const out = [];
let version = '1.0';
let effective = '';

for (const d of DOCS) {
  const { value } = await mammoth.extractRawText({ path: join(root, 'public/legal', d.file) });
  const body = clean(value);
  out.push({ ...d, body });
  // Parse version / effective date from whichever doc carries them (the ToS).
  const vm = body.match(/Version\s+([0-9]+(?:\.[0-9]+)*)/i);
  if (vm && d.id === 'terms') version = vm[1];
  const em = body.match(/Effective\s+([A-Za-z]+\s+[0-9]{1,2},\s+[0-9]{4})/);
  if (em && d.id === 'terms') effective = em[1];
}

const ts = `// AUTO-GENERATED by scripts/gen-legal.mjs from public/legal/*.docx — do not edit by hand.
// Re-run \`node scripts/gen-legal.mjs\` after updating the .docx source, then commit both.

export interface LegalDoc {
  id: string;
  title: string;
  file: string; // filename under public/legal/ (download URL is /legal/<file>)
  body: string;
}

export const LEGAL_VERSION = ${JSON.stringify(version)};
export const LEGAL_EFFECTIVE = ${JSON.stringify(effective)};

export const LEGAL_DOCS: LegalDoc[] = ${JSON.stringify(out, null, 2)};
`;

writeFileSync(join(root, 'utils/dara/legal-content.ts'), ts, 'utf8');
console.log(
  `Wrote utils/dara/legal-content.ts — version ${version}, effective ${effective || '(none)'}, ${out.length} docs.`
);
